version: 2.1
orbs:
  node: circleci/node@5.1.0

workflows:
    planthor-fe-ci :
      jobs:
        - node/run:
            app-dir: ./
            cache-version: v1
            npm-run: build
            pkg-manager: npm
            resource_class: large

        - node/test:
            app-dir: ./
            cache-version: v1
            pkg-manager: npm
            resource_class: large
            run-command: test
            test-results-for: other
            requires:
                - node/run